name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux:
    name: build linux binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Build (${{ matrix.arch }})
        env:
          CGO_ENABLED: '0'
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
        run: |
          mkdir -p dist
          go build -trimpath -ldflags "-s -w" -o dist/nexus-proxy-server ./proxy-server

      - name: Package (${{ matrix.arch }})
        run: |
          cp config.example.yaml dist/
          tar -czf dist/nexus-proxy-server_linux_${{ matrix.arch }}.tar.gz -C dist nexus-proxy-server -C dist config.example.yaml
          rm -f dist/config.example.yaml dist/nexus-proxy-server

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}
          path: dist/nexus-proxy-server_linux_${{ matrix.arch }}.tar.gz

  publish:
    name: publish release
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Flatten artifact files
        run: |
          shopt -s globstar
          mkdir -p upload
          mv dist/**/nexus-proxy-server_linux_*.tar.gz upload/
          cd upload
          sha256sum nexus-proxy-server_linux_*.tar.gz > SHA256SUMS

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            upload/nexus-proxy-server_linux_*.tar.gz
            upload/SHA256SUMS
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

